### PR TITLE
Update docs for version 0.8.93

### PR DESCRIPTION
**Pull request by antonsoroko**

### CODE REVIEW

**Comment by antonsoroko** [comment]
After this PR would be merged we also need to merge https://github.com/antonsoroko/docs-book-partners/pull/1

**Comment by ghanna2017** [comment]
Thanks @antonsoroko

**Comment by ghanna2017** [comment]
Hi @antonsoroko , I've copied over your subnav changes to the partners book. We don't usually merge PRs in that repo. So you can delete your  antonsoroko/docs-book-partners#1 branch now. Thanks!

Gigi

**Comment by antonsoroko** [comment]
@ghanna2017 
Hi!
I created that PR because of instruction posted in this message https://github.com/pivotal-cf/docs-altoros-heartbeat/issues/5#issuecomment-321211308

Also, as I can see, right now https://github.com/pivotal-cf/docs-book-partners/blob/master/master_middleman/source/subnavs/altoros-heartbeat_subnav.erb is broken, because it should contain `/partners/` uri part in links (as I can see in other files), but now it does not.

**Comment by antonsoroko** [comment]
@ghanna2017 We have sent new release to pivnet. Please do not forget to fix links in https://github.com/pivotal-cf/docs-book-partners/blob/master/master_middleman/source/subnavs/altoros-heartbeat_subnav.erb . Thank you!

**Comment by ghanna2017** [comment]
Thanks, Anton. Looks like it was fixed overnight. For some reason I
couldn't merge your PR for the subnav in the partners book... I assumed it
was due to some restriction for that repo. Glad the links were fixed.

Thanks, Gigi

**Comment by antonsoroko** [comment]
@ghanna2017 
Hi. Thanks!
About
>For some reason I couldn't merge your PR for the subnav in the partners book...

it was my fault - I haven’t noticed that I created PR not in your repo but in my fork :-)

**Pull request merged**
